repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: check-symlinks
    -   id: check-added-large-files
    -   id: detect-private-key

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1      # Insert the latest tag here
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
    -   id: commitizen

-   repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.97.4
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
        exclude: '^modules/[^/]+/[^/]+$'
        args:
        -   --tf-init-args=-backend=false
    -   id: terraform_tflint
        exclude: ^examples
        args:
        -   --args=--config=__GIT_WORKING_DIR__/.config/tflint.hcl
        -   --env-vars=TFLINT_LOG="info"
    -   id: terraform_docs
        args:
        -   --hook-config=--config=__GIT_WORKING_DIR__/.config/terraform-docs.yml
